### ISSUE TITLE
[TFX Standard Components Walkthrough] 

### ISSUE THREAD

**Issue by muhammadyaseen** [GoogleCloudPlatform/mlops-on-gcp#183]
In lab ''TFX Standard Components Walkthrough'' task#4  ''Clone the example repo within your AI Platform Notebooks instance'' can't be completed becaue the versions used in the intall script are too old.

Specifically, the command

```git clone https://github.com/GoogleCloudPlatform/mlops-on-gcp
cd mlops-on-gcp/workshops/tfx-caip-tf23
./install.sh
```
results in error, even specifically mentioned the library version via `pip install` doesn't work. I think this lab needs to be updated to be compatible with currently supported versions.

**Comment by GdRottoli** [comment]
Same error here.

The output for the ./install.sh script is:
```shell
ERROR: Ignored the following versions that require a different python version: 0.12.0rc0 Requires-Python >=2.7,<3; 0.24.0 Requires-Python >=3.6,<3.9; 0.24.0rc0 Requires-Python >=3.6,<3.9; 0.24.0rc1 Requires-Python >=3.6,<3.9; 0.24.1 Requires-Python >=3.6,<3.9; 0.25.0 Requires-Python >=3.6,<3.9; 0.25.0rc0 Requires-Python >=3.6,<3.9; 0.25.0rc1 Requires-Python >=3.6,<3.9; 0.25.0rc2 Requires-Python >=3.6,<3.9; 0.26.0 Requires-Python >=3.6,<3.9; 0.26.0rc0 Requires-Python >=3.6,<3.9; 0.26.1 Requires-Python >=3.6,<3.9; 0.26.3 Requires-Python >=3.6,<3.9; 0.26.4 Requires-Python >=3.6,<3.9; 0.27.0 Requires-Python >=3.6,<3.9; 0.27.0rc0 Requires-Python >=3.6,<3.9; 0.28.0 Requires-Python >=3.6,<3.9; 0.28.0rc0 Requires-Python >=3.6,<3.9; 0.29.0 Requires-Python >=3.6,<3.9; 0.29.0rc0 Requires-Python >=3.6,<3.9; 0.30.0 Requires-Python >=3.6,<3.9; 0.30.0rc0 Requires-Python >=3.6,<3.9; 0.30.1 Requires-Python >=3.6,<3.9; 0.30.2 Requires-Python >=3.6,<3.9; 1.0.0 Requires-Python >=3.6,<3.9; 1.0.0rc0 Requires-Python >=3.6,<3.9; 1.0.0rc1 Requires-Python >=3.6,<3.9; 1.0.0rc2 Requires-Python >=3.6,<3.9; 1.10.0 Requires-Python >=3.7,<3.10; 1.10.0rc0 Requires-Python >=3.7,<3.10; 1.11.0 Requires-Python >=3.7,<3.10; 1.11.0rc0 Requires-Python >=3.7,<3.10; 1.12.0 Requires-Python >=3.7,<3.10; 1.12.0rc0 Requires-Python >=3.7,<3.10; 1.13.0 Requires-Python >=3.8,<3.10; 1.13.0rc0 Requires-Python >=3.8,<3.10; 1.2.0 Requires-Python >=3.6,<3.9; 1.2.0rc0 Requires-Python >=3.6,<3.9; 1.2.1 Requires-Python >=3.6,<3.9; 1.3.0 Requires-Python >=3.6,<3.9; 1.3.0rc0 Requires-Python >=3.6,<3.9; 1.3.1 Requires-Python >=3.6,<3.9; 1.3.2 Requires-Python >=3.6,<3.9; 1.3.3 Requires-Python >=3.6,<3.9; 1.3.4 Requires-Python >=3.6,<3.9; 1.4.0 Requires-Python >=3.7,<3.9; 1.4.0rc0 Requires-Python >=3.7,<3.9; 1.4.1 Requires-Python >=3.7,<3.9; 1.5.0 Requires-Python >=3.7,<3.9; 1.5.0rc0 Requires-Python >=3.7,<3.9; 1.5.1 Requires-Python >=3.7,<3.9; 1.6.0 Requires-Python >=3.7,<3.9; 1.6.0rc0 Requires-Python >=3.7,<3.9; 1.6.1 Requires-Python >=3.7,<3.9; 1.6.2 Requires-Python >=3.7,<3.9; 1.7.0 Requires-Python >=3.7,<3.9; 1.7.0rc0 Requires-Python >=3.7,<3.9; 1.7.1 Requires-Python >=3.7,<3.9; 1.7.2 Requires-Python >=3.7,<3.9; 1.8.0 Requires-Python >=3.7,<3.10; 1.8.0rc0 Requires-Python >=3.7,<3.10; 1.8.0rc1 Requires-Python >=3.7,<3.10; 1.8.1 Requires-Python >=3.7,<3.10; 1.9.0 Requires-Python >=3.7,<3.10; 1.9.0rc0 Requires-Python >=3.7,<3.10; 1.9.1 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement tfx==0.25.0 (from versions: 0.13.0rc0, 0.13.0rc1, 0.13.0rc2, 0.13.0, 0.14.0rc1, 0.14.0, 0.15.0rc0, 0.15.0, 0.21.0rc0, 0.21.0, 0.21.1, 0.21.2, 0.21.3, 0.21.4, 0.21.5, 0.22.0rc0, 0.22.0, 0.22.1rc1, 0.22.1, 0.22.2, 0.23.0rc0, 0.23.0, 0.23.1)
ERROR: No matching distribution found for tfx==0.25.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 77.4M  100 77.4M    0     0   169M      0 --:--:-- --:--:-- --:--:--  169M
404 Client Error: Not Found for url: http://metadata/computeMetadata/v1/instance/attributes/notebook-enable-debug
404 Client Error: Not Found for url: http://metadata/computeMetadata/v1/instance/attributes/runtime-resource-name
404 Client Error: Not Found for url: http://metadata/computeMetadata/v1/instance/attributes/disable-check-xsrf
404 Client Error: Not Found for url: http://metadata/computeMetadata/v1/instance/attributes/use-collaborative
404 Client Error: Not Found for url: http://metadata/computeMetadata/v1/instance/attributes/notebook-disable-downloads
404 Client Error: Not Found for url: http://metadata/computeMetadata/v1/instance/attributes/notebook-disable-terminal
404 Client Error: Not Found for url: http://metadata/computeMetadata/v1/instance/attributes/notebook-enable-delete-to-trash
404 Client Error: Not Found for url: http://metadata/computeMetadata/v1/instance/attributes/jupyter-user
404 Client Error: Not Found for url: http://metadata/computeMetadata/v1/instance/attributes/notebook-enable-gateway-client
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-nbextension", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/jupyter_core/application.py", line 285, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py", line 1043, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.10/site-packages/notebook/nbextensions.py", line 972, in start
    super().start()
  File "/opt/conda/lib/python3.10/site-packages/jupyter_core/application.py", line 274, in start
    self.subapp.start()
  File "/opt/conda/lib/python3.10/site-packages/notebook/nbextensions.py", line 882, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/opt/conda/lib/python3.10/site-packages/notebook/nbextensions.py", line 855, in toggle_nbextension_python
    return toggle(module,
  File "/opt/conda/lib/python3.10/site-packages/notebook/nbextensions.py", line 470, in enable_nbextension_python
    return _set_nbextension_state_python(True, module, user, sys_prefix,
  File "/opt/conda/lib/python3.10/site-packages/notebook/nbextensions.py", line 368, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/opt/conda/lib/python3.10/site-packages/notebook/nbextensions.py", line 1107, in _get_nbextension_metadata
    m = import_item(module)
  File "/opt/conda/lib/python3.10/site-packages/traitlets/utils/importstring.py", line 38, in import_item
    return __import__(parts[0])
ModuleNotFoundError: No module named 'tensorflow_model_analysis'
```

**Comment by georgehalasi** [comment]
Also reported the above issue to Qwiklabs Support, but it seems like this has not yet been fixed. Is there any other workaround available?

**Comment by muhammadyaseen** [comment]
Hi @georgehalasi,
> Also reported the above issue to Qwiklabs Support, but it seems like this has not yet been fixed. Is there any other workaround available?

I don't think there is a workaround possible. As I mentioned, using the new library APIs it is possible to complete the tasks. But the problem is that Qwiklabs have to update their grading code at their end to be compatible with the new libraries. AFAIK, we can't bypass this check. 

I waited a long time to get any reasonable response from them but then cancelled my subscription.
