### ISSUE TITLE
workshops/tfx-caip-tf23/lab-02-tfx-pipeline training fails and last two lab checkpoints cannot be satisfied

### ISSUE THREAD

**Issue by MrCsabaToth** [GoogleCloudPlatform/mlops-on-gcp#192]
The pipeline training step run failure should not affect the last two lab checkpoints, since those are about creating the pipeline, and then creating the pipeline run, which both can be done.

The training failed consistently with this error:
```
2023-10-11 22:58:12.754996: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib 2023-10-11 22:58:12.755050: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine. INFO:absl:tensorflow_ranking is not available: No module named 'tensorflow_ranking' INFO:absl:tensorflow_text is not available: No module named 'tensorflow_text' INFO:absl:Running driver for Trainer INFO:absl:MetadataStore with gRPC connection initialized INFO:absl:Adding KFP pod name tfx-covertype-continuous-training-5dgkz-1098609175 to execution WARNING:absl:Output artifact uri gs://qwiklabs-gcp-03-5dccd98592cf-kubeflowpipelines-default/tfx_covertype_continuous_training/6f668ff0-7c57-452e-ac0c-d58ccf3f5e91/Trainer/model/8 already exists WARNING:absl:Output artifact uri gs://qwiklabs-gcp-03-5dccd98592cf-kubeflowpipelines-default/tfx_covertype_continuous_training/6f668ff0-7c57-452e-ac0c-d58ccf3f5e91/Trainer/model_run/8 already exists INFO:absl:Running executor for Trainer INFO:absl:Attempting to infer TFX Python dependency for beam INFO:absl:Copying all content from install dir /tfx-src/tfx to temp dir /tmp/tmpy3xv2o2f/build/tfx INFO:absl:Generating a temp setup file at /tmp/tmpy3xv2o2f/build/tfx/setup.py INFO:absl:Creating temporary sdist package, logs available at /tmp/tmpy3xv2o2f/build/tfx/setup.log INFO:absl:Added --extra_package=/tmp/tmpy3xv2o2f/build/tfx/dist/tfx_ephemeral-0.25.0.tar.gz to beam args INFO:absl:json_inputs='{"examples": [{"artifact": {"id": "5", "type_id": "18", "uri": "gs://qwiklabs-gcp-03-5dccd98592cf-kubeflowpipelines-default/tfx_covertype_continuous_training/6f668ff0-7c57-452e-ac0c-d58ccf3f5e91/Transform/transformed_examples/4", "properties": {"split_names": {"string_value": "[\"train\", \"eval\"]"}}, "custom_properties": {"state": {"string_value": "published"}, "producer_component": {"string_value": "Transform"}, "name": {"string_value": "transformed_examples"}}, "state": "LIVE", "create_time_since_epoch": "1697064805628", "last_update_time_since_epoch": "1697064896890"}, "artifact_type": {"id": "18", "name": "Examples", "properties": {"split_names": "STRING", "span": "INT", "version": "INT"}}, "__artifact_class_module__": "tfx.types.standard_artifacts", "__artifact_class_name__": "Examples"}], "schema": [{"artifact": {"id": "1", "type_id": "16", "uri": "schema", "create_time_since_epoch": "1697064728453", "last_update_time_since_epoch": "1697064728453"}, "artifact_type": {"id": "16", "name": "Schema"}, "__artifact_class_module__": "tfx.types.standard_artifacts", "__artifact_class_name__": "Schema"}], "transform_graph": [{"artifact": {"id": "4", "type_id": "22", "uri": "gs://qwiklabs-gcp-03-5dccd98592cf-kubeflowpipelines-default/tfx_covertype_continuous_training/6f668ff0-7c57-452e-ac0c-d58ccf3f5e91/Transform/transform_graph/4", "custom_properties": {"name": {"string_value": "transform_graph"}, "state": {"string_value": "published"}, "producer_component": {"string_value": "Transform"}}, "state": "LIVE", "create_time_since_epoch": "1697064805625", "last_update_time_since_epoch": "1697064896888"}, "artifact_type": {"id": "22", "name": "TransformGraph"}, "__artifact_class_module__": "tfx.types.standard_artifacts", "__artifact_class_name__": "TransformGraph"}]}'. INFO:absl:json_outputs='{"model": [{"artifact": {"id": "11", "type_id": "28", "uri": "gs://qwiklabs-gcp-03-5dccd98592cf-kubeflowpipelines-default/tfx_covertype_continuous_training/6f668ff0-7c57-452e-ac0c-d58ccf3f5e91/Trainer/model/8", "custom_properties": {"name": {"string_value": "model"}, "producer_component": {"string_value": "Trainer"}}}, "artifact_type": {"id": "28", "name": "Model"}, "__artifact_class_module__": "tfx.types.standard_artifacts", "__artifact_class_name__": "Model"}], "model_run": [{"artifact": {"id": "12", "type_id": "29", "uri": "gs://qwiklabs-gcp-03-5dccd98592cf-kubeflowpipelines-default/tfx_covertype_continuous_training/6f668ff0-7c57-452e-ac0c-d58ccf3f5e91/Trainer/model_run/8", "custom_properties": {"name": {"string_value": "model_run"}, "producer_component": {"string_value": "Trainer"}}}, "artifact_type": {"id": "29", "name": "ModelRun"}, "__artifact_class_module__": "tfx.types.standard_artifacts", "__artifact_class_name__": "ModelRun"}]}'. INFO:absl:json_exec_properties='{"custom_config": "{\"ai_platform_training_args\": {\"masterConfig\": {\"imageUri\": \"gcr.io/qwiklabs-gcp-03-5dccd98592cf/tfx_covertype_continuous_training@sha256:861db0475ced0a414a550e8d36edafb9f9e5d646e34dc884bcec35802e099cb9\"}, \"project\": \"qwiklabs-gcp-03-5dccd98592cf\", \"region\": \"us-central1-f\", \"serviceAccount\": \"tfx-tuner-caip-service-account@qwiklabs-gcp-03-5dccd98592cf.iam.gserviceaccount.com\"}}", "eval_args": "{\"num_steps\": 500}", "kfp_pod_name": "tfx-covertype-continuous-training-5dgkz-1098609175", "module_file": "model.py", "run_fn": null, "train_args": "{\"num_steps\": 5000}", "trainer_fn": null}'. WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth Traceback (most recent call last): File "/usr/local/lib/python3.7/dist-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect from google.appengine.api import memcache ModuleNotFoundError: No module named 'google.appengine' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.7/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in from oauth2client.contrib.locked_file import LockedFile ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.7/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in from oauth2client.locked_file import LockedFile ModuleNotFoundError: No module named 'oauth2client.locked_file' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.7/dist-packages/googleapiclient/discovery_cache/__init__.py", line 42, in autodetect from . import file_cache File "/usr/local/lib/python3.7/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in "file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth" ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/ml/v1/rest INFO:absl:TrainingInput={'masterConfig': {'imageUri': 'gcr.io/qwiklabs-gcp-03-5dccd98592cf/tfx_covertype_continuous_training@sha256:861db0475ced0a414a550e8d36edafb9f9e5d646e34dc884bcec35802e099cb9', 'containerCommand': ['python', '-m', 'tfx.scripts.run_executor', '--executor_class_path', 'tfx.components.trainer.executor.GenericExecutor', '--inputs', '{"examples": [{"artifact": {"id": "5", "type_id": "18", "uri": "gs://qwiklabs-gcp-03-5dccd98592cf-kubeflowpipelines-default/tfx_covertype_continuous_training/6f668ff0-7c57-452e-ac0c-d58ccf3f5e91/Transform/transformed_examples/4", "properties": {"split_names": {"string_value": "[\\"train\\", \\"eval\\"]"}}, "custom_properties": {"state": {"string_value": "published"}, "producer_component": {"string_value": "Transform"}, "name": {"string_value": "transformed_examples"}}, "state": "LIVE", "create_time_since_epoch": "1697064805628", "last_update_time_since_epoch": "1697064896890"}, "artifact_type": {"id": "18", "name": "Examples", "properties": {"split_names": "STRING", "span": "INT", "version": "INT"}}, "__artifact_class_module__": "tfx.types.standard_artifacts", "__artifact_class_name__": "Examples"}], "schema": [{"artifact": {"id": "1", "type_id": "16", "uri": "schema", "create_time_since_epoch": "1697064728453", "last_update_time_since_epoch": "1697064728453"}, "artifact_type": {"id": "16", "name": "Schema"}, "__artifact_class_module__": "tfx.types.standard_artifacts", "__artifact_class_name__": "Schema"}], "transform_graph": [{"artifact": {"id": "4", "type_id": "22", "uri": "gs://qwiklabs-gcp-03-5dccd98592cf-kubeflowpipelines-default/tfx_covertype_continuous_training/6f668ff0-7c57-452e-ac0c-d58ccf3f5e91/Transform/transform_graph/4", "custom_properties": {"name": {"string_value": "transform_graph"}, "state": {"string_value": "published"}, "producer_component": {"string_value": "Transform"}}, "state": "LIVE", "create_time_since_epoch": "1697064805625", "last_update_time_since_epoch": "1697064896888"}, "artifact_type": {"id": "22", "name": "TransformGraph"}, "__artifact_class_module__": "tfx.types.standard_artifacts", "__artifact_class_name__": "TransformGraph"}]}', '--outputs', '{"model": [{"artifact": {"id": "11", "type_id": "28", "uri": "gs://qwiklabs-gcp-03-5dccd98592cf-kubeflowpipelines-default/tfx_covertype_continuous_training/6f668ff0-7c57-452e-ac0c-d58ccf3f5e91/Trainer/model/8", "custom_properties": {"name": {"string_value": "model"}, "producer_component": {"string_value": "Trainer"}}}, "artifact_type": {"id": "28", "name": "Model"}, "__artifact_class_module__": "tfx.types.standard_artifacts", "__artifact_class_name__": "Model"}], "model_run": [{"artifact": {"id": "12", "type_id": "29", "uri": "gs://qwiklabs-gcp-03-5dccd98592cf-kubeflowpipelines-default/tfx_covertype_continuous_training/6f668ff0-7c57-452e-ac0c-d58ccf3f5e91/Trainer/model_run/8", "custom_properties": {"name": {"string_value": "model_run"}, "producer_component": {"string_value": "Trainer"}}}, "artifact_type": {"id": "29", "name": "ModelRun"}, "__artifact_class_module__": "tfx.types.standard_artifacts", "__artifact_class_name__": "ModelRun"}]}', '--exec-properties', '{"custom_config": "{\\"ai_platform_training_args\\": {\\"masterConfig\\": {\\"imageUri\\": \\"gcr.io/qwiklabs-gcp-03-5dccd98592cf/tfx_covertype_continuous_training@sha256:861db0475ced0a414a550e8d36edafb9f9e5d646e34dc884bcec35802e099cb9\\"}, \\"project\\": \\"qwiklabs-gcp-03-5dccd98592cf\\", \\"region\\": \\"us-central1-f\\", \\"serviceAccount\\": \\"tfx-tuner-caip-service-account@qwiklabs-gcp-03-5dccd98592cf.iam.gserviceaccount.com\\"}}", "eval_args": "{\\"num_steps\\": 500}", "kfp_pod_name": "tfx-covertype-continuous-training-5dgkz-1098609175", "module_file": "model.py", "run_fn": null, "train_args": "{\\"num_steps\\": 5000}", "trainer_fn": null}']}, 'region': 'us-central1-f', 'serviceAccount': 'tfx-tuner-caip-service-account@qwiklabs-gcp-03-5dccd98592cf.iam.gserviceaccount.com'} INFO:absl:Submitting job='tfx_20231011225820', project='qwiklabs-gcp-03-5dccd98592cf' to AI Platform. INFO:googleapiclient.discovery:URL being requested: POST https://ml.googleapis.com/v1/projects/qwiklabs-gcp-03-5dccd98592cf/jobs?alt=json Traceback (most recent call last): File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 360, in main() File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 353, in main execution_info = launcher.launch() File "/tfx-src/tfx/orchestration/launcher/base_component_launcher.py", line 209, in launch copy.deepcopy(execution_decision.exec_properties)) File "/tfx-src/tfx/orchestration/launcher/in_process_component_launcher.py", line 72, in _run_executor copy.deepcopy(input_dict), output_dict, copy.deepcopy(exec_properties)) File "/tfx-src/tfx/extensions/google_cloud_ai_platform/trainer/executor.py", line 85, in Do job_id) File "/tfx-src/tfx/extensions/google_cloud_ai_platform/runner.py", line 305, in start_aip_training job_labels=job_labels) File "/tfx-src/tfx/extensions/google_cloud_ai_platform/runner.py", line 145, in _launch_aip_training request.execute() File "/usr/local/lib/python3.7/dist-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper return wrapped(*args, **kwargs) File "/usr/local/lib/python3.7/dist-packages/googleapiclient/http.py", line 898, in execute raise HttpError(resp, content, uri=self.uri) googleapiclient.errors.HttpError:
```

**Comment by MrCsabaToth** [comment]
Note, that if I use us-central1-a zone and location instead of the randomly picked zone/location by the lab it succeeds. So somewhere in the lab checkpoint check code us-central1-a left hard-coded instead of the variable
